Support for ZPL_JSON_INDENT_STYLE_COMPACT
zpl-c/zpl pull request #114
Opened 2023-07-23 17:01 UTC by rheatley-pervasid

I've had this in my local copy for a while and kept forgetting to contribute back.
We need to be able to generate "compact" JSON, so no extra newlines or spaces. It seemed nicer to generate it correctly, rather than strip newlines and spaces after.

Let me know if you feel I should tidy any thing up.

2023-07-23 17:24 UTC, zpl-zak requested changes
Looks great! The ability to write compact JSON is worth having.

My only concern is that this will break output for special formats, like [SJSON](https://help.autodesk.com/view/Stingray/ENU/?guid=__stingray_help_managing_content_sjson_html):
```lua
foo = 123
bar = "baz"
cfg = {
  version = ["a", "b", "c"]
}
```

but that only affects newlines, so we could additionally pass the node itself inside zpl__json_string_eol and do as follows:
```c
static ZPL_ALWAYS_INLINE const char *zpl__json_string_eol(zpl_adt_node *node, zpl_isize indent) {
    #if !defined(ZPL_PARSER_DISABLE_ANALYSIS)
        if (node->delim_style != ZPL_ADT_DELIM_STYLE_COMMA)
            return "\n";
    #endif
    return indent == ZPL_JSON_INDENT_STYLE_COMPACT ? "" : "\n";
}
```

2023-07-23 17:24 UTC, zpl-zak commented on package.json
This file does not need to be updated, as it updates itself when we deploy a new release. You can, however, add a new entry in the CHANGELOG file.

2023-07-24 08:50 UTC, rheatley-pervasid commented
Hopefuly that works for you? I removed what would have been unnecessary calls to zpl__json_string_eol() for the non-comma delimited cases.

2023-07-24 09:36 UTC, zpl-zak approved these changes
Thank you for the contrib, again!

2023-07-24 09:38 UTC, zpl-zak commented on package.json
No problem at all! In case you ever need to build complete zpl.h again, but without going through the release flow, you can launch `misc/embed_file.sh` to produce one.

2023-07-24 09:39 UTC, merged